// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTxUJ_z_O9TdzWErYBa34xcSNucG_vztY',
    appId: '1:900595641168:web:94422ad6fa072d60d75a55',
    messagingSenderId: '900595641168',
    projectId: 'fasumdiki-app',
    authDomain: 'fasumdiki-app.firebaseapp.com',
    storageBucket: 'fasumdiki-app.appspot.com',
    measurementId: 'G-C0DV8NGHZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAP-1f8pgcnEasS3LsvwEI2Ya54EpdLWo',
    appId: '1:900595641168:android:e056fa7df45146acd75a55',
    messagingSenderId: '900595641168',
    projectId: 'fasumdiki-app',
    storageBucket: 'fasumdiki-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARBWeA28QaXoyr-V0-saMsdGv-roUV0as',
    appId: '1:900595641168:ios:2dc9809e5b2f8291d75a55',
    messagingSenderId: '900595641168',
    projectId: 'fasumdiki-app',
    storageBucket: 'fasumdiki-app.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARBWeA28QaXoyr-V0-saMsdGv-roUV0as',
    appId: '1:900595641168:ios:2dc9809e5b2f8291d75a55',
    messagingSenderId: '900595641168',
    projectId: 'fasumdiki-app',
    storageBucket: 'fasumdiki-app.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTxUJ_z_O9TdzWErYBa34xcSNucG_vztY',
    appId: '1:900595641168:web:fb360334db3abf75d75a55',
    messagingSenderId: '900595641168',
    projectId: 'fasumdiki-app',
    authDomain: 'fasumdiki-app.firebaseapp.com',
    storageBucket: 'fasumdiki-app.appspot.com',
    measurementId: 'G-BYKNGMTZBL',
  );
}
